#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtomcrypt
Version  : 1.18.2
Release  : 1
URL      : https://github.com/libtom/libtomcrypt/releases/download/v1.18.2/crypt-1.18.2.tar.xz
Source0  : https://github.com/libtom/libtomcrypt/releases/download/v1.18.2/crypt-1.18.2.tar.xz
Summary  : public domain open source cryptographic toolkit
Group    : Development/Tools
License  : WTFPL
Requires: libtomcrypt-license = %{version}-%{release}

%description
# libtomcrypt
Previously the git repository contained `doc/crypt.pdf` for detailed documentation.
This was changed and the file is now only available from the tarball of the appropriate version
or from the page https://github.com/libtom/libtomcrypt/releases .

%package license
Summary: license components for the libtomcrypt package.
Group: Default

%description license
license components for the libtomcrypt package.


%prep
%setup -q -n libtomcrypt-1.18.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560525237
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1560525237
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libtomcrypt
cp LICENSE %{buildroot}/usr/share/package-licenses/libtomcrypt/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libtomcrypt/LICENSE
